baseURL: "http://homepages.see.leeds.ac.uk/~georjb/predictive-analytics/"
languageCode: en-gb
title: Predictive Analytics
theme: "ath-tufte-hugo_18-19"
canonifyURLs: true
relativeURLs: true
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: R
      url: /install/
      weight: 3
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Roger Beecham
  thumbnail: ./images/geog5927m.png
  instructor:
    name: Dr. Roger Beecham
    email: r.j.beecham@leeds.ac.uk
    url: "http://www.roger-beecham.com"
    twitter: rjbeecham
    github: rogerbeecham
    office: 10.139 Manton
  course:
    number: GEOG5927M
    semester: Autumn/Winter 2019
    days: "Mon (lec) & Weds (lab)"
    time: "2:00pm-4:00pm (lec)"
    location: "Roger Stevens LT25 (12.25)"
    twitter: rjbeecham
    dates: "November 11–December 11, 2019"
    github: "rogerbeecham"
    copyrightYear: "2019"
     # contactDetails: >-
     #  Office hours: By appointment.
  university:
    name: University of Leeds
    url: "https://www.leeds.ac.uk"
  school:
    name: School of Geography
    url: "https://environment.leeds.ac.uk/geography"
  description: "Introduces techniques for simulating and predicting social behaviour"
  primaryColor: "#a50f15"
  secondaryColor: "#ef3b2c"
  # credits: >-
  #   Hex icon by Roger Beecham, using [`hexSticker`](https://github.com/GuangchuangYu/hexSticker).
  logo:
    url: ./images/geog5927m.png
    alt: Predictive Analytics
  meta:
    twitterSite: "@rjbeecham"
    twitterCreator: "@rjbeecham"
