baseURL: "https://www.roger-beecham.com/predictive-analytics/"
languageCode: en-gb
title: Predictive Analytics
theme: "rjb-tufte-hugo"
canonifyURLs: false
relativeURLs: true
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  # - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: R
      url: /install/
      weight: 3
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Roger Beecham
  thumbnail: ./images/geog5927m.png
  instructor:
    name: Dr. Roger Beecham
    email: r.j.beecham@leeds.ac.uk
    url: "http://www.roger-beecham.com"
    twitter: rjbeecham
    github: rogerbeecham
    office: 10.139 Manton
  course:
    number: GEOG5927M
    semester: Spring 2022
    days: "Mon (lec) & Weds (lab) & Fri (recap)"
    time: "3:00pm-4:00pm (lec)"
    location: "Online | Cohen labs"
    twitter: rjbeecham
    dates: "Feb 28–Apr 27, 2022"
    github: "rogerbeecham"
    copyrightYear: "2022"
  university:
    name: University of Leeds
    url: "https://www.leeds.ac.uk"
  school:
    name: School of Geography
    url: "https://environment.leeds.ac.uk/geography"
  description: "Introduces techniques for simulating and predicting social behaviour"
  primaryColor: "#252525"
  secondaryColor: "#737373"
  logo:
    url: ./images/geog5927m.png
    alt: Predictive Analytics
  meta:
    twitterSite: "@rjbeecham"
    twitterCreator: "@rjbeecham"
