---
title: Syllabus
slug: syllabus
citeproc: false
bibliography: ../static/bib/references.bib
csl: ../static/bib/chicago-syllabus-no-bib.csl
---

```{r load-libraries, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

[^courseinfo] Combining theory and practical examples, this module introduces Predictive Analytics via two geocomputational techniques in which University of Leeds Geography specialises: spatial microsimulation, machine learning and agent-based modelling. You will apply these techniques through project work highly relevant to the consumer analytics domain and using modern data analysis environments.

[^courseinfo]:
  `r blogdown::shortcode("courseinfo")`

By the end of this module you should be able to:

- explain and critically evaluate the role of spatial analytics and geocomputational modelling in simulating and predicting consumer behaviours
- apply geocomputational modelling and simulation techniques on real data sets
- devise an analysis strategy for the implementation of sophisticated modelling tools to
address business problems, presenting and justifying recommendations in an appropriate context

The full module handbook can be downloaded from the VLE.

# Assignments and dates

You can find full descriptions for all the assignments on the VLE.

There are two assignments: an individual project report and a group-work presenation.

The <span class="newthought">individual project report</span> is related to Practicals 1, 2 and 3. The word limit is 2,000 words plus four images^[Each of these images are the equivalent of 250 words. Therefore this assessment is termed ‘3,000 word equivalent’. The written text within your report must not exceed the 2,000 word limit.]. The deadline for submitting this report is **2pm** on **Thursday 24th March 2022** (week 22 of semester 2). The project report is worth 75% of your overall module mark.

The <span class="newthought">group presentations</span> will be set during the ABM workshop (Practical 4). It requires you to undertake group work and prepare a presentation which will be completed in advance of a timetabled session on **Wednesday 27th April 2022** (week 23 of semester 2). The group presentation is worth 25% of your overall module mark.


# Navigating the course materials

The home for this module is [this website](../../). From here, you will find the course [Schedule](/schedule/), where for each session there is <i class="fas fa-book-reader"></i> **reading**, <i class="fas fa-laptop-code"></i> **practical** and <i class="fas fa-university"></i> **lecture** content. Also accompanying each session is an [R Markdown](https://rmarkdown.rstudio.com/) file with a template to complete practical activities. These session templates contain pre-prepared code chunks for you to execute.


# Slack

 I have set up a module [Slack](https://predictiveana-tfa4522.slack.com), which should provide a useful mechanism for sharing information, resources and discussing practical and assignment activity.

If you've not used Slack before, then follow these pages on [getting started with Slack](https://slack.com/intl/en-gb/help/articles/218080037-Getting-started-for-new-members). You should post all substantive questions associated with the module to Slack. These will get answered. If you wish to discuss more personal matters around your completing the course, then send those directly to me via e-mail (r.j.beecham@leeds.ac.uk).


# Technologies and resources

## R and RStudio

You will use [R](https://cran.r-project.org/) and the [RStudio](https://www.rstudio.com/) IDE for most of this module's practical work and for Assignment 1. You have already had some introduction to R through LUBS5308 _Business Analytics and Decision Science_ and GEOG5917 Big Data and Consumer Analytics.

If you have not done already, you should download R and and RStudio on your personal machines. [**These introductory pages**](/install/), should help. You should certainly have the latest version of R and RStudio on your machines prior to starting practical 1.

## Online help

You will discover through this module the benefits of working with data programatically -- programming environments such as R and Python are increasingly a requirement for modern data analysis. However, you may also find that there is initially a steeper learning curve when compared with point-and-click software tools such as SPSS and ArcGIS.

There are many online resources to help support your learning. Two important resources are:

- [StackOverflow](https://stackoverflow.com/), a site where questions and answers are posted to all sorts of programming questions

- [RStudio Community](https://community.rstudio.com/), a site for people using RStudio and the `tidyverse` (see the [R](/install/) pages)
